import time

num1 = 34
num2 = 45.78

print("")
time.sleep(0.8)
print("Imprimiendo tipo de variable de la variable num1:")
time.sleep(0.8)
print(type(num1))
time.sleep(0.8)
print("Imprimiendo valor de variable num1:")
time.sleep(0.8)
print(num1)
time.sleep(0.8)
print("")
print("Espaciando.")
time.sleep(0.2)
print("Espaciando..")
time.sleep(0.2)
print("Espaciando...")
time.sleep(0.2)
print("Espaciando....")
time.sleep(0.2)
print("")
time.sleep(0.8)
print("Imprimiendo tipo de variable de la variable num2:")
time.sleep(0.8)
print(type(num2))
time.sleep(0.8)
print("Imprimiendo valor de num2")
time.sleep(0.8)
print(num2)
time.sleep(0.8)
print("")
time.sleep(0.8)
print("")
print("Cambiando variable num1 a flotante y imprimiendo valor de num1")
time.sleep(0.8)
print("")
print(float(num1))
time.sleep(0.8)
print("")
time.sleep(0.8)
print("impriendo tipo de variable de num1")
time.sleep(0.8)
print("")
print(type(float(num1)))
time.sleep(0.8)
print("")
time.sleep(0.8)
print("Cambiando y imprimiendo num2")
time.sleep(0.8)
print("")
time.sleep(0.5)
print(int(num2))
time.sleep(0.8)
print("")
time.sleep(0.8)
print("Imprimiendo tipo de variable de num2")
time.sleep(0.8)
print("")
print(type(int(num2)))